In [103]:
import pandas as pd
import numpy as np
import wget
df.head()

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -122.23     37.88                  41          880           129.0   
1    -122.22     37.86                  21         7099          1106.0   
2    -122.24     37.85                  52         1467           190.0   
3    -122.25     37.85                  52         1274           235.0   
4    -122.25     37.85                  52         1627           280.0   

   population  households  median_income  median_house_value ocean_proximity  
0         322         126         8.3252              452600        NEAR BAY  
1        2401        1138         8.3014              358500        NEAR BAY  
2         496         177         7.2574              352100        NEAR BAY  
3         558         219         5.6431              341300        NEAR BAY  
4         565         259         3.8462              342200        NEAR BAY

**Answer for the first question**

In [33]:
pd.__version__

'2.0.3'

**Answer for the second question**

In [34]:
df = pd.read_csv("Book1.csv")
df.shape[1]

10

**Answer for the third question**

In [35]:
df.count()

longitude             20640
latitude              20640
housing_median_age    20640
total_rooms           20640
total_bedrooms        20433
population            20640
households            20640
median_income         20640
median_house_value    20640
ocean_proximity       20640
dtype: int64

In [36]:
missing_values = df.isnull().sum()
columns_with_missing_values = missing_values[missing_values > 0]
print(columns_with_missing_values)

total_bedrooms    207
dtype: int64


**Answer for the fourth question**

In [38]:
print(" Number of unique values in column ocean_proximity:", df["ocean_proximity"].nunique())
print(" Unqiue values in column ocean_proximity:", df["ocean_proximity"].unique())

 Number of unique values in column ocean_proximity: 5
 Unqiue values in column ocean_proximity: ['NEAR BAY' '<1H OCEAN' 'INLAND' 'NEAR OCEAN' 'ISLAND']


**Answer for the fifth question**

In [75]:
Houses_near_bay = df[df["ocean_proximity"] == "NEAR BAY"]
Houses_near_bay["median_house_value"].mean()

259212.31179039303

In [77]:
Houses_near_bay.isnull().sum()

longitude              0
latitude               0
housing_median_age     0
total_rooms            0
total_bedrooms        20
population             0
households             0
median_income          0
median_house_value     0
ocean_proximity        0
dtype: int64

In [71]:
df_null = df[df["total_bedrooms"].isnull()]
df_null = df_null[df_null["ocean_proximity"] == "NEAR BAY" ]
df_null.shape

(20, 10)

**Answer for the sixth question**

In [86]:
pre_fill_mean = df["total_bedrooms"].mean()
post_fill_mean = df["total_bedrooms"].fillna(fill_mean).mean()

In [87]:
print("Mean post fillna:", post_fill_mean)
print("Mean pre fillna:", pre_fill_mean)

Mean post fillna: 537.8705525375617
Mean pre fillna: 537.8705525375618


**Answer for the seventh question**

In [123]:
df_island = df[df["ocean_proximity"] == "ISLAND"] 
df_columns = df_island[["housing_median_age", "total_rooms", "total_bedrooms"]]
X = df_columns.values
XTX = np.dot( X.T, X)
inv_XTX = np.linalg.inv(XTX)
inv_XTX

array([[ 9.19403586e-04, -3.66412216e-05,  5.43072261e-05],
       [-3.66412216e-05,  8.23303633e-06, -2.77534485e-05],
       [ 5.43072261e-05, -2.77534485e-05,  1.00891325e-04]])

In [119]:
y = np.array([950, 1300, 800, 1000, 1300])
y

array([ 950, 1300,  800, 1000, 1300])

In [125]:
w = np.dot(np.dot(inv_XTX,X.T),y)
w

array([23.12330961, -1.48124183,  5.69922946])